# Generated by Django 6.0.2 on 2026-02-20 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrix_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='스냅샷의 고유 이름', max_length=200)),
                ('snapshot_data', models.JSONField(default=dict, help_text='{ "messages": [ChatMessage 객체 배열] }')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='fabrix_chat.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memory_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory Snapshot',
                'verbose_name_plural': 'Memory Snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fabrix_chat_user_id_0ccd15_idx'), models.Index(fields=['chat_session', 'name'], name='fabrix_chat_chat_se_662fb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_session', 'name'), name='unique_snapshot_name_per_session', violation_error_message='이미 존재하는 스냅샷 이름입니다.')],
            },
        ),
    ]
