# Generated by GitHub Copilot on 2026-03-11

from django.db import migrations, models


SEED_ROWS = [
    {
        'dashboard_name': '매출 현황 대시보드',
        'url': 'https://public.tableau.com/views/SalesDashboard',
        'linkname': '매출 현황',
        'desc': '월별/분기별 매출 추이 및 지역별 분석',
    },
    {
        'dashboard_name': '재고 관리 대시보드',
        'url': 'https://public.tableau.com/views/InventoryDashboard',
        'linkname': '재고 관리',
        'desc': '실시간 재고 현황 및 입출고 모니터링',
    },
    {
        'dashboard_name': '고객 분석 대시보드',
        'url': 'https://public.tableau.com/views/CustomerAnalytics',
        'linkname': '고객 분석',
        'desc': '고객 세그먼트 및 구매 패턴 분석',
    },
    {
        'dashboard_name': 'KPI 종합 현황판',
        'url': 'https://public.tableau.com/views/KPIDashboard',
        'linkname': 'KPI 현황',
        'desc': '주요 성과지표 실시간 모니터링',
    },
]


def seed_dashboard_links(apps, schema_editor):
    DashboardLink = apps.get_model('fabrix_chat', 'DashboardLink')
    DashboardLink.objects.bulk_create([
        DashboardLink(
            display_order=index + 1,
            dashboard_name=row['dashboard_name'],
            url=row['url'],
            linkname=row['linkname'],
            desc=row['desc'],
        )
        for index, row in enumerate(SEED_ROWS)
    ])


def clear_dashboard_links(apps, schema_editor):
    DashboardLink = apps.get_model('fabrix_chat', 'DashboardLink')
    DashboardLink.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fabrix_chat', '0002_memorysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(db_index=True, unique=True)),
                ('dashboard_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('linkname', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['display_order'],
                'indexes': [
                    models.Index(fields=['display_order'], name='fabrix_chat_display_7f9eb0_idx'),
                    models.Index(fields=['-updated_at'], name='fabrix_chat_updated_55c95f_idx'),
                ],
            },
        ),
        migrations.RunPython(seed_dashboard_links, clear_dashboard_links),
    ]