# Generated by Django 6.0.2 on 2026-03-17 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrix_chat', '0003_dashboardlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardlink',
            new_name='fabrix_chat_display_1f8c7d_idx',
            old_name='fabrix_chat_display_7f9eb0_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardlink',
            new_name='fabrix_chat_updated_8de143_idx',
            old_name='fabrix_chat_updated_55c95f_idx',
        ),
    ]
