# Generated by Django 6.0.2 on 2026-04-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrix_chat', '0004_rename_fabrix_chat_display_7f9eb0_idx_fabrix_chat_display_1f8c7d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dashboardlink',
            name='fabrix_chat_display_1f8c7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='dashboardlink',
            name='fabrix_chat_updated_8de143_idx',
        ),
        migrations.DeleteModel(
            name='DashboardLink',
        ),
    ]
