# Generated by Django 6.0.3 on 2026-04-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrix_chat', '0005_remove_dashboardlink_fabrix_chat_display_1f8c7d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
