# Generated by Django 6.0.2 on 2026-04-08 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeLogSheetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='main', max_length=32, unique=True)),
                ('workbook_data', models.JSONField(default=list)),
                ('revision', models.BigIntegerField(default=0)),
                ('source_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pe_log_sheet_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PE Log Sheet State',
                'verbose_name_plural': 'PE Log Sheet States',
            },
        ),
        migrations.CreateModel(
            name='PeLogSheetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_revision', models.BigIntegerField()),
                ('new_revision', models.BigIntegerField()),
                ('ops', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pe_log_sheet_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pe_log_sheet.pelogsheetstate')),
            ],
            options={
                'verbose_name': 'PE Log Sheet Revision',
                'verbose_name_plural': 'PE Log Sheet Revisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
