# Generated by Django 6.0.2 on 2026-04-02 02:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('category_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('waiting', '대기 중'), ('working', '변환 중'), ('completed', '완료'), ('failed', '실패')], default='waiting', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callback_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='doc_uploade_status_0a394d_idx'), models.Index(fields=['created_at'], name='doc_uploade_created_e90b5f_idx')],
            },
        ),
    ]
