# Generated by Django 6.0.2 on 2026-02-13 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExplorerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the preset', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the visualization')),
                ('data_config', models.JSONField(help_text='Data loading configuration (filename, selected columns)')),
                ('chart_spec', models.JSONField(help_text='Graphic Walker IChart specification')),
                ('fields_meta', models.JSONField(help_text='Field metadata for schema reconstruction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(help_text='Owner of this preset', on_delete=django.db.models.deletion.CASCADE, related_name='data_explorer_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Explorer Preset',
                'verbose_name_plural': 'Data Explorer Presets',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='data_explor_user_id_8753b7_idx'), models.Index(fields=['user', '-created_at'], name='data_explor_user_id_a52fe9_idx')],
            },
        ),
    ]
