# Generated by Django 6.0.2 on 2026-02-13 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_explorer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexplorerpreset',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, this preset is visible to all users'),
        ),
        migrations.AddIndex(
            model_name='dataexplorerpreset',
            index=models.Index(fields=['is_public', '-updated_at'], name='data_explor_is_publ_075e3d_idx'),
        ),
    ]
