# Generated by Django 6.0.2 on 2026-03-12 13:31

import apps.board.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_display', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('header_background_image', models.FileField(blank=True, null=True, upload_to=apps.board.models.board_header_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_create', models.BooleanField(default=True)),
                ('allow_update', models.BooleanField(default=True)),
                ('allow_delete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ['title_display', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='board.board')),
            ],
            options={
                'verbose_name': 'Board Post',
                'verbose_name_plural': 'Board Posts',
                'ordering': ['-updated_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BoardPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.board.models.post_image_upload_path)),
                ('sort_order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.boardpost')),
            ],
            options={
                'verbose_name': 'Board Post Image',
                'verbose_name_plural': 'Board Post Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderatorships', to='board.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_moderatorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board Moderator',
                'verbose_name_plural': 'Board Moderators',
                'ordering': ['board__title_display', 'user__username'],
                'unique_together': {('board', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['board', '-updated_at'], name='board_board_board_i_68b7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['board', '-created_at'], name='board_board_board_i_ab81b2_idx'),
        ),
    ]
