# Generated by Django 6.0.2 on 2026-03-17 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_seed_default_boards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_style',
            field=models.CharField(choices=[('tile', '타일형'), ('reddit', 'Reddit형')], default='tile', max_length=20),
        ),
        migrations.CreateModel(
            name='BoardPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.boardpost')),
            ],
            options={
                'verbose_name': 'Board Post Comment',
                'verbose_name_plural': 'Board Post Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='board_board_post_id_3792c4_idx')],
            },
        ),
    ]
